// Package datafs embeds the structured-data yaml files generated by
// cmd/gendoors and cmd/genmeta. It is deliberately a tiny standalone
// package so consumers (e.g. pkg/data) can import it without pulling in
// the ebiten/X11 transitive dependency that lives in the parent assets
// package.
package datafs

import "embed"

// FS contains every yaml file in this directory at build time.
// Files: tile_meta.yaml / monsters.yaml / tts_index.yaml / ...
//
//go:embed *.yaml
var FS embed.FS
