// Command gendoors scans the assets/image/* sheets, detects the yellow door
// brackets on each tile, and emits assets/doors_gen.go holding the result so
// the game does not need to rescan pixels at runtime.
//
// Run from the project root:
//
//	go run ./cmd/gendoors > assets/doors_gen.go
package main

import (
	"fmt"
	"image"
	_ "image/jpeg"
	_ "image/png"
	"os"
	"sort"
)

// --- detection constants (must match what the game gameplay was tuned with) ---

const (
	doorBandRatio   = 0.25
	doorYellowRatio = 0.004
)

// isDoorYellow matches the door bracket color used in the artwork. The brackets
// are not pure (255,255,0) yellow; many pixels (especially anti-aliased edges
// and JPEG-compressed regions) sit around (213,166,0) — a saturated
// orange-yellow. We accept any pixel that is bright in red+green and very low
// in blue, while still rejecting the brown wood floor whose red channel is
// well below 200.
func isDoorYellow(r8, g8, b8 int) bool {
	return r8 > 200 && g8 > 150 && b8 < 80 && r8-b8 > 100
}

func bandYellowRatio(img image.Image, x0, y0, x1, y1 int) float64 {
	if x1 <= x0 || y1 <= y0 {
		return 0
	}
	yellow, total := 0, 0
	for y := y0; y < y1; y++ {
		for x := x0; x < x1; x++ {
			r, g, b, _ := img.At(x, y).RGBA()
			if isDoorYellow(int(r>>8), int(g>>8), int(b>>8)) {
				yellow++
			}
			total++
		}
	}
	if total == 0 {
		return 0
	}
	return float64(yellow) / float64(total)
}

func detectDoors(img image.Image, rect image.Rectangle) [4]bool {
	w := rect.Dx()
	h := rect.Dy()
	bandX := int(float64(w) * doorBandRatio)
	if bandX < 4 {
		bandX = 4
	}
	bandY := int(float64(h) * doorBandRatio)
	if bandY < 4 {
		bandY = 4
	}
	var doors [4]bool
	doors[0] = bandYellowRatio(img, rect.Min.X, rect.Min.Y, rect.Max.X, rect.Min.Y+bandY) > doorYellowRatio
	doors[1] = bandYellowRatio(img, rect.Max.X-bandX, rect.Min.Y, rect.Max.X, rect.Max.Y) > doorYellowRatio
	doors[2] = bandYellowRatio(img, rect.Min.X, rect.Max.Y-bandY, rect.Max.X, rect.Max.Y) > doorYellowRatio
	doors[3] = bandYellowRatio(img, rect.Min.X, rect.Min.Y, rect.Min.X+bandX, rect.Max.Y) > doorYellowRatio
	return doors
}

func isBlank(img image.Image, rect image.Rectangle) bool {
	step := rect.Dx() / 16
	if step < 1 {
		step = 1
	}
	nonBlack := 0
	for y := rect.Min.Y; y < rect.Max.Y; y += step {
		for x := rect.Min.X; x < rect.Max.X; x += step {
			r, g, bl, _ := img.At(x, y).RGBA()
			if int(r>>8)+int(g>>8)+int(bl>>8) > 30 {
				nonBlack++
				if nonBlack > 4 {
					return false
				}
			}
		}
	}
	return true
}

func anyDoor(d [4]bool) bool {
	for _, v := range d {
		if v {
			return true
		}
	}
	return false
}

// --- sheet processing ---

type entry struct {
	ID    int
	Note  string
	Doors [4]bool
}

func loadImage(path string) image.Image {
	f, err := os.Open(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "open %s: %v\n", path, err)
		os.Exit(1)
	}
	defer f.Close()
	img, _, err := image.Decode(f)
	if err != nil {
		fmt.Fprintf(os.Stderr, "decode %s: %v\n", path, err)
		os.Exit(1)
	}
	return img
}

func cellRect(img image.Image, cols, rows, c, r int) image.Rectangle {
	b := img.Bounds()
	tw := b.Dx() / cols
	th := b.Dy() / rows
	x0 := b.Min.X + c*tw
	y0 := b.Min.Y + r*th
	return image.Rect(x0, y0, x0+tw, y0+th)
}

func processSheet(path string, cols, rows, idBase int, kind string, out *[]entry, force func(idx int, doors *[4]bool, note *string)) {
	img := loadImage(path)
	for r := 0; r < rows; r++ {
		for c := 0; c < cols; c++ {
			idx := r*cols + c
			rect := cellRect(img, cols, rows, c, r)
			if isBlank(img, rect) {
				continue
			}
			d := detectDoors(img, rect)
			note := fmt.Sprintf("%s r%d c%d", kind, r, c)
			if force != nil {
				force(idx, &d, &note)
			}
			if !anyDoor(d) {
				continue
			}
			*out = append(*out, entry{ID: idBase + idx, Doors: d, Note: note})
		}
	}
}

func main() {
	var out []entry

	processSheet("assets/image/入口大厅.png", 3, 1, 1000, "starter", &out,
		func(idx int, d *[4]bool, note *string) {
			// The Grand Staircase tile (idx 0) has no yellow brackets in
			// the artwork; its visible staircase implies a south door.
			if idx == 0 && !anyDoor(*d) {
				d[2] = true
				*note += " (manual: down door from staircase)"
			}
		})

	processSheet("assets/image/主地图.jpg", 10, 5, 0, "base", &out, nil)
	processSheet("assets/image/扩展地图.jpg", 10, 2, 500, "extension", &out, nil)

	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })

	fmt.Println("// Code generated by cmd/gendoors. DO NOT EDIT.")
	fmt.Println("// Run `go run ./cmd/gendoors > assets/doors_gen.go` to regenerate.")
	fmt.Println()
	fmt.Println("package assets")
	fmt.Println()
	fmt.Println("// tileDoors maps each valid tile ID to its door layout at rotation 0.")
	fmt.Println("// Side order: [up, right, down, left]. IDs not present in this map")
	fmt.Println("// are blank artwork cells or had no detectable doors and are skipped.")
	fmt.Println("var tileDoors = map[int][4]bool{")
	for _, e := range out {
		fmt.Printf("\t%-5d: {%-5v, %-5v, %-5v, %-5v}, // %s\n",
			e.ID, e.Doors[0], e.Doors[1], e.Doors[2], e.Doors[3], e.Note)
	}
	fmt.Println("}")
}
