// genxls parses the legacy .xls game tables and emits structured yaml under
// assets/datafs/.
//
//   assets/raw/小黑屋/真相表.xls       -> assets/datafs/omens.yaml
//   assets/raw/小黑屋/奸徒身份表.xls   -> assets/datafs/scenarios_index.yaml
//
// Both source files are old BIFF (.xls) workbooks. We use the pure-Go
// extrame/xls library; no external tooling (LibreOffice / etc.) is required.
//
// Run:  go run ./cmd/genxls
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/extrame/xls"
)

// English names for the 13 omens, in the same column order as the 真相表.xls
// header row. Hard-coded because the spreadsheet only has Chinese names.
var omenEN = map[string]string{
	"噬咬":  "Bite",
	"书本":  "Book",
	"水晶球": "Crystal Ball",
	"脏狗":  "Dog",
	"女孩":  "Girl",
	"圣符":  "Holy Symbol",
	"疯汉":  "Madman",
	"面具":  "Mask",
	"徽章":  "Medallion",
	"戒指":  "Ring",
	"颅骨":  "Skull",
	"长矛":  "Spear",
	"灵板":  "Spirit Board",
}

type omen struct {
	NameCN string
	NameEN string
}

type room struct {
	NameCN string
	NameEN string
}

type omensFile struct {
	Omens  []omen
	Rooms  []room
	Matrix [][]int // matrix[ri][oi] = scenarioID
}

type scenarioEntry struct {
	ID      int
	Traitor string
}

func main() {
	rawDir := flag.String("raw", "assets/raw/小黑屋", "directory holding the .xls source files")
	outDir := flag.String("out", "assets/datafs", "directory to write yaml into")
	flag.Parse()

	if err := os.MkdirAll(*outDir, 0o755); err != nil {
		die("mkdir %s: %v", *outDir, err)
	}

	omens, err := parseOmens(filepath.Join(*rawDir, "真相表.xls"))
	if err != nil {
		die("parseOmens: %v", err)
	}
	if err := writeFile(filepath.Join(*outDir, "omens.yaml"), emitOmens(omens)); err != nil {
		die("write omens.yaml: %v", err)
	}
	fmt.Fprintf(os.Stderr, "omens.yaml: %d omens × %d rooms\n",
		len(omens.Omens), len(omens.Rooms))

	scenarios, err := parseScenarios(filepath.Join(*rawDir, "奸徒身份表.xls"))
	if err != nil {
		die("parseScenarios: %v", err)
	}
	if err := writeFile(filepath.Join(*outDir, "scenarios_index.yaml"), emitScenarios(scenarios)); err != nil {
		die("write scenarios_index.yaml: %v", err)
	}
	fmt.Fprintf(os.Stderr, "scenarios_index.yaml: %d scenarios\n", len(scenarios))
}

// ---------- 真相表.xls ----------

func parseOmens(path string) (*omensFile, error) {
	wb, err := xls.Open(path, "utf-8")
	if err != nil {
		return nil, fmt.Errorf("open %s: %w", path, err)
	}
	sheet := wb.GetSheet(0)
	if sheet == nil {
		return nil, fmt.Errorf("%s: sheet 0 missing", path)
	}

	// Row 1 is the header: ["房 间", "", "噬咬", "书本", ..., "灵板"].
	// Note there is an empty separator column between "房 间" and the first
	// omen, so we cannot assume omens start at Col(1). Instead we track each
	// omen's actual column index so the data rows can be read with the same
	// alignment.
	header := sheet.Row(1)
	if header == nil {
		return nil, fmt.Errorf("%s: header row missing", path)
	}
	headerLast := int(header.LastCol())
	omens := make([]omen, 0, 13)
	omenCols := make([]int, 0, 13)
	for c := 1; c <= headerLast; c++ {
		raw := strings.TrimSpace(header.Col(c))
		if raw == "" {
			continue
		}
		omens = append(omens, omen{NameCN: raw, NameEN: omenEN[raw]})
		omenCols = append(omenCols, c)
	}

	// Rows 3..15 are room rows. Cell 0 contains "中文名\n英文名" (sometimes
	// with extra spaces); the scenario IDs sit at the same column indices as
	// the corresponding omen in the header.
	rooms := make([]room, 0, 13)
	matrix := make([][]int, 0, 13)
	maxRow := int(sheet.MaxRow)
	for r := 3; r <= maxRow; r++ {
		row := sheet.Row(r)
		if row == nil {
			continue
		}
		cn, en := splitRoomName(row.Col(0))
		if cn == "" {
			continue
		}
		ids := make([]int, len(omenCols))
		for i, col := range omenCols {
			n, _ := strconv.Atoi(strings.TrimSpace(row.Col(col)))
			ids[i] = n
		}
		rooms = append(rooms, room{NameCN: cn, NameEN: en})
		matrix = append(matrix, ids)
	}

	return &omensFile{Omens: omens, Rooms: rooms, Matrix: matrix}, nil
}

// splitRoomName splits a cell like "荒废的房间\nAbandoned Room" into ("荒废的房间", "Abandoned Room").
// Whitespace and trailing punctuation are trimmed. If no second line exists, en is empty.
func splitRoomName(s string) (cn, en string) {
	s = strings.TrimSpace(s)
	if s == "" {
		return "", ""
	}
	// Cells use \n inside-cell line break.
	parts := strings.SplitN(s, "\n", 2)
	cn = strings.TrimSpace(parts[0])
	if len(parts) == 2 {
		en = strings.TrimSpace(parts[1])
	}
	return cn, en
}

func emitOmens(o *omensFile) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by cmd/genxls from assets/raw/小黑屋/真相表.xls.\n")
	b.WriteString("# DO NOT edit by hand; rerun `go run ./cmd/genxls`.\n")
	b.WriteString("# matrix[ri][oi] = scenario_id, where ri indexes rooms[]\n")
	b.WriteString("# and oi indexes omens[]. Used at Haunt-roll time:\n")
	b.WriteString("#   given (omen_card, current_room) -> look up scenario.\n\n")

	b.WriteString("omens:\n")
	for _, o := range o.Omens {
		fmt.Fprintf(&b, "  - { name_cn: %q, name_en: %q }\n", o.NameCN, o.NameEN)
	}

	b.WriteString("\nrooms:\n")
	for _, r := range o.Rooms {
		fmt.Fprintf(&b, "  - { name_cn: %q, name_en: %q }\n", r.NameCN, r.NameEN)
	}

	b.WriteString("\nmatrix:\n")
	for _, row := range o.Matrix {
		strs := make([]string, len(row))
		for i, v := range row {
			strs[i] = strconv.Itoa(v)
		}
		fmt.Fprintf(&b, "  - [%s]\n", strings.Join(strs, ", "))
	}
	return b.String()
}

// ---------- 奸徒身份表.xls ----------

// parseScenarios reads 奸徒身份表.xls and returns the 50 scenarios with their
// traitor-target description. The sheet is laid out in 4 column-pairs of
// (id, traitor) repeating 13 times vertically.
func parseScenarios(path string) ([]scenarioEntry, error) {
	wb, err := xls.Open(path, "utf-8")
	if err != nil {
		return nil, fmt.Errorf("open %s: %w", path, err)
	}
	sheet := wb.GetSheet(0)
	if sheet == nil {
		return nil, fmt.Errorf("%s: sheet 0 missing", path)
	}

	out := make([]scenarioEntry, 0, 50)
	maxRow := int(sheet.MaxRow)
	for r := 2; r <= maxRow; r++ {
		row := sheet.Row(r)
		if row == nil {
			continue
		}
		// 4 column-pairs: (0,1) (2,3) (4,5) (6,7)
		for pair := 0; pair < 4; pair++ {
			idCol := pair * 2
			descCol := idCol + 1
			idStr := strings.TrimSpace(row.Col(idCol))
			desc := strings.TrimSpace(row.Col(descCol))
			if idStr == "" {
				continue
			}
			id, err := strconv.Atoi(idStr)
			if err != nil {
				continue // not a scenario row (e.g. stray text)
			}
			out = append(out, scenarioEntry{ID: id, Traitor: desc})
		}
	}

	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out, nil
}

func emitScenarios(scs []scenarioEntry) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by cmd/genxls from assets/raw/小黑屋/奸徒身份表.xls.\n")
	b.WriteString("# DO NOT edit by hand; rerun `go run ./cmd/genxls`.\n")
	b.WriteString("# Each scenario has a numeric id (1..50) and a Chinese\n")
	b.WriteString("# description of who the traitor is. Names like\n")
	b.WriteString("# \"揭露者\" mean the player who triggered the haunt.\n\n")
	b.WriteString("scenarios:\n")
	for _, s := range scs {
		fmt.Fprintf(&b, "  - { id: %d, traitor: %q }\n", s.ID, s.Traitor)
	}
	return b.String()
}

// ---------- helpers ----------

func writeFile(path, content string) error {
	return os.WriteFile(path, []byte(content), 0o644)
}

func die(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "genxls: "+format+"\n", args...)
	os.Exit(1)
}
