// Command genmeta reads the TTS workshop save (assets/raw/Workshop/*.json)
// and emits structured Chinese-name dictionaries used by later stages of the
// project (haunt scenarios, monster spawning, token placement).
//
// Outputs (under assets/data/):
//
//	monsters.yaml   — colour-grouped monster pawn list (e.g. "红色怪物1")
//	tts_index.yaml  — full (kind, nickname, guid) dump of every named TTS
//	                  object; serves as a lookup dictionary for future
//	                  hand-curation work.
//
// Run from the project root:
//
//	go run ./cmd/genmeta
//
// genmeta only depends on encoding/json + os/regexp, so it works in CI without
// X11 / ebiten just like cmd/gendoors.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// node mirrors only the TTS object fields we care about. Extra fields in the
// JSON are ignored thanks to encoding/json's default behaviour.
type node struct {
	Name             string `json:"Name"`
	Nickname         string `json:"Nickname"`
	GUID             string `json:"GUID"`
	Description      string `json:"Description"`
	ContainedObjects []node `json:"ContainedObjects"`
	States           map[string]node
}

// We unmarshal States separately because TTS uses arbitrary numeric keys.
type rawNode struct {
	Name             string                     `json:"Name"`
	Nickname         string                     `json:"Nickname"`
	GUID             string                     `json:"GUID"`
	Description      string                     `json:"Description"`
	ContainedObjects []json.RawMessage          `json:"ContainedObjects"`
	States           map[string]json.RawMessage `json:"States"`
}

func decodeNode(raw json.RawMessage) (node, error) {
	var rn rawNode
	if err := json.Unmarshal(raw, &rn); err != nil {
		return node{}, err
	}
	n := node{
		Name:        rn.Name,
		Nickname:    rn.Nickname,
		GUID:        rn.GUID,
		Description: rn.Description,
	}
	for _, child := range rn.ContainedObjects {
		c, err := decodeNode(child)
		if err != nil {
			return node{}, err
		}
		n.ContainedObjects = append(n.ContainedObjects, c)
	}
	if rn.States != nil {
		n.States = map[string]node{}
		for k, v := range rn.States {
			c, err := decodeNode(v)
			if err != nil {
				return node{}, err
			}
			n.States[k] = c
		}
	}
	return n, nil
}

type tts struct {
	ObjectStates []json.RawMessage `json:"ObjectStates"`
}

// walk emits every named (Nickname != "") node, depth-first, in encounter order.
func walk(n node, out *[]node) {
	if n.Nickname != "" {
		*out = append(*out, n)
	}
	for _, c := range n.ContainedObjects {
		walk(c, out)
	}
	for _, c := range n.States {
		walk(c, out)
	}
}

// ---------- yaml writers (hand-rolled, no yaml.v3 dep here) ----------

func yamlQuote(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// writeFile writes content under dir, creating dir if needed.
func writeFile(dir, name, content string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	p := filepath.Join(dir, name)
	return os.WriteFile(p, []byte(content), 0o644)
}

// ---------- monsters.yaml ----------

// monsterRe matches "<color>怪物<N>" e.g. "红色怪物1", "玫红色怪物6".
// Capturing groups: 1=color, 2=number.
var monsterRe = regexp.MustCompile(`^(红色|橙色|绿色|蓝色|紫色|玫红色|黄色)怪物([0-9]+)$`)

type monster struct {
	Number int
	GUID   string
}

func emitMonsters(nodes []node) string {
	groups := map[string][]monster{}
	for _, n := range nodes {
		m := monsterRe.FindStringSubmatch(n.Nickname)
		if m == nil {
			continue
		}
		num := 0
		fmt.Sscanf(m[2], "%d", &num)
		groups[m[1]] = append(groups[m[1]], monster{Number: num, GUID: n.GUID})
	}

	colors := []string{"红色", "橙色", "绿色", "蓝色", "紫色", "玫红色", "黄色"}

	var b strings.Builder
	b.WriteString("# Auto-generated by cmd/genmeta from assets/raw/Workshop/831685264.json.\n")
	b.WriteString("# Chinese monster pawn pool grouped by colour. Each entry is one\n")
	b.WriteString("# physical pawn in the TTS mod. The numbering starts at 1 within a\n")
	b.WriteString("# colour and matches the pawn's printed label.\n")
	b.WriteString("# Counts (red 24, orange 24, green 16, blue 9, purple 6, magenta 6,\n")
	b.WriteString("# yellow 6) follow the published rulebook.\n")
	b.WriteString("monsters:\n")
	for _, c := range colors {
		ms := groups[c]
		if len(ms) == 0 {
			continue
		}
		sort.Slice(ms, func(i, j int) bool { return ms[i].Number < ms[j].Number })
		fmt.Fprintf(&b, "  - color: %s\n", yamlQuote(c))
		fmt.Fprintf(&b, "    count: %d\n", len(ms))
		b.WriteString("    pawns:\n")
		for _, m := range ms {
			fmt.Fprintf(&b, "      - { number: %d, guid: %s }\n", m.Number, yamlQuote(m.GUID))
		}
	}
	return b.String()
}

// ---------- tts_index.yaml ----------

// emitTTSIndex dumps every uniquely-named entity once. Duplicate Nicknames
// (player pawn copies, repeated monster groups visiting States) are merged
// onto the first occurrence's GUID for simplicity. Subsequent stages can join
// on Nickname directly.
func emitTTSIndex(nodes []node) string {
	type rec struct {
		Nickname    string
		Kind        string
		GUID        string
		Description string
	}
	seen := map[string]bool{}
	var recs []rec
	for _, n := range nodes {
		// Skip empty nicknames (anonymous deck slots) and obvious duplicates.
		if n.Nickname == "" {
			continue
		}
		key := n.Nickname + "|" + n.GUID
		if seen[key] {
			continue
		}
		seen[key] = true
		recs = append(recs, rec{
			Nickname:    n.Nickname,
			Kind:        n.Name,
			GUID:        n.GUID,
			Description: n.Description,
		})
	}
	sort.SliceStable(recs, func(i, j int) bool {
		if recs[i].Nickname != recs[j].Nickname {
			return recs[i].Nickname < recs[j].Nickname
		}
		return recs[i].GUID < recs[j].GUID
	})

	var b strings.Builder
	b.WriteString("# Auto-generated by cmd/genmeta. Full index of named entities in\n")
	b.WriteString("# the TTS workshop save, sorted by nickname for diff-friendliness.\n")
	b.WriteString("# Each unique (nickname, guid) is listed once; multiple identical\n")
	b.WriteString("# guids may share the same nickname when TTS uses State variants.\n")
	b.WriteString("entities:\n")
	for _, r := range recs {
		fmt.Fprintf(&b, "  - nickname: %s\n", yamlQuote(r.Nickname))
		fmt.Fprintf(&b, "    kind: %s\n", yamlQuote(r.Kind))
		fmt.Fprintf(&b, "    guid: %s\n", yamlQuote(r.GUID))
		if r.Description != "" {
			oneLine := strings.ReplaceAll(r.Description, "\r\n", " ")
			oneLine = strings.ReplaceAll(oneLine, "\n", " ")
			oneLine = strings.TrimSpace(oneLine)
			if oneLine != "" {
				fmt.Fprintf(&b, "    description: %s\n", yamlQuote(oneLine))
			}
		}
	}
	return b.String()
}

// ---------- main ----------

func main() {
	src := flag.String("src", "assets/raw/Workshop/831685264.json",
		"path to the TTS workshop json save")
	outDir := flag.String("out", "assets/datafs",
		"output directory for the generated yaml files")
	flag.Parse()

	data, err := os.ReadFile(*src)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read %s: %v\n", *src, err)
		os.Exit(1)
	}
	var t tts
	if err := json.Unmarshal(data, &t); err != nil {
		fmt.Fprintf(os.Stderr, "parse %s: %v\n", *src, err)
		os.Exit(1)
	}

	var all []node
	for _, raw := range t.ObjectStates {
		n, err := decodeNode(raw)
		if err != nil {
			fmt.Fprintf(os.Stderr, "decode object: %v\n", err)
			os.Exit(1)
		}
		walk(n, &all)
	}

	monstersYAML := emitMonsters(all)
	if err := writeFile(*outDir, "monsters.yaml", monstersYAML); err != nil {
		fmt.Fprintf(os.Stderr, "write monsters.yaml: %v\n", err)
		os.Exit(1)
	}

	indexYAML := emitTTSIndex(all)
	if err := writeFile(*outDir, "tts_index.yaml", indexYAML); err != nil {
		fmt.Fprintf(os.Stderr, "write tts_index.yaml: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "genmeta: %d named entities, wrote monsters.yaml + tts_index.yaml under %s\n",
		len(all), *outDir)
}
